name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Archive JAR file
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download JAR file
      uses: actions/download-artifact@v3
      with:
        name: java-app

    - name: Trigger Jenkins Job
      run: |
        curl -X POST ${{ secrets.JENKINS_URL }}/job/InsuredAssurance/build \
        --user ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} \
        --data-urlencode json='{"parameter": [{"name":"JAR_FILE", "value":"$(ls target/*.jar)"}]}'
      env:
        JENKINS_URL: ${{ secrets.JENKINS_URL }}
        JENKINS_USER: ${{ secrets.JENKINS_USER }}
        JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
